### ISSUE TITLE
Cant pass PHPUNIT assertSame

### ISSUE THREAD

**Issue by ianrussel** [archwisp/PHPEncryptData#24]
Hi, any help how would you test or make pass a test like this? It seems that everytime I run phpunit, encrypted data changes

      ` /**
    * @test
    */
       public function check_if_user_email_is_decrypted()
      {
   		$userEmail = $this->encryptor->encrypt('ako@yahoo.com');
   		//var_dump($userEmail);//"MHxnZjI5dkQ5WUV4L2Y3azd4V3c2YzJ4TkxUR1Rjb0x6ckR1RjVFbWdHSktNSmRqWDVJQT09fEdxKzdCUTEvZVB2Q2ZNVGdMNjJ0RFE9PQ=="
   		$this->assertSame("MHxnZjI5dkQ5WUV4L2Y3azd4V3c2YzJ4TkxUR1Rjb0x6ckR1RjVFbWdHSktNSmRqWDVJQT09fEdxKzdCUTEvZVB2Q2ZNVGdMNjJ0RFE9PQ==",$userEmail);
      }`

**Comment by archwisp** [comment]
Hey there,

The problem you are having is due to the fact that encrypt(), by design, will return different ciphertext for the same plaintext because the IV is randomly generated. This is to prevent certain types of attacks. In cases where you *must* be able to re-produce the same ciphertext, you must supply the IV that was used to encrypt the plaintext the first time: encrypt($plaintext, $iv);

**Comment by ianrussel** [comment]
Thank you very much @archwisp
